import {readFileSync,existsSync,realpathSync} from 'node:fs';
import {resolve,sep} from 'node:path';
export function validate(config,data,examDir){
 const errors=[],warnings=[],issue=(ok,message)=>{if(!ok)errors.push(message);};
 const idOK=x=>typeof x==='string'&&/^[a-z0-9][a-z0-9._-]*$/.test(x);
 const map=(list,kind)=>{issue(Array.isArray(list),kind+' doit être une liste');const out=new Map();for(const x of list||[]){issue(idOK(x.id),kind+' : identifiant invalide');issue(!out.has(x.id),kind+' : identifiant dupliqué '+x.id);out.set(x.id,x);}return out;};
 issue(config.schemaVersion===1&&data.schemaVersion===1,'Version de schéma non prise en charge');issue(idOK(config.examId),'examId invalide');issue(typeof config.title==='string'&&config.title.length>0,'Titre absent');issue(typeof config.contentVersion==='string'&&idOK(config.contentVersion),'Version de contenu invalide');issue(Number.isInteger(config.storageVersion)&&config.storageVersion>0,'Version de sauvegarde invalide');issue(Number.isInteger(config.miniQuizSize)&&config.miniQuizSize>0,'Taille de mini-quiz invalide');
 const lessons=map(data.lessons,'Leçon'),questions=map(data.questions,'Question'),objectives=map(data.objectives,'Objectif'),documents=map(data.documents,'Document'),inventory=map(data.inventory,'Inventaire'),activities=map(data.activities,'Activité');
 issue(lessons.size>0&&questions.size>0&&objectives.size>0,'Le contenu ne peut pas être vide');
 const resources=data.resources||{},assets={};
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';');
 const safeMarkup=(s,label)=>{issue(!/<\s*(script|iframe|object|embed|link|style|base|form)\b|\son\w+\s*=|javascript\s*:|<\/script|url\s*\(/i.test(s),'HTML actif interdit : '+label);issue(!/(?:src|href)\s*=\s*["']\s*(?:https?:|\/\/|file:)/i.test(s),'Ressource externe interdite : '+label);};
 for(const [id,r] of Object.entries(resources)){
  issue(idOK(id),'Identifiant ressource invalide '+id);const path=resolve(examDir,r.path||''),base=resolve(examDir)+sep;issue(path.startsWith(base),'Ressource hors du dossier : '+id);if(!path.startsWith(base)||!existsSync(path)){errors.push('Ressource manquante : '+id);continue;}if(!realpathSync(path).startsWith(realpathSync(examDir)+sep)){errors.push('Lien hors du dossier : '+id);continue;}
  if(r.kind==='html'||r.kind==='svg'){assets[id]=readFileSync(path,'utf8');safeMarkup(assets[id],id);if(r.kind==='svg')issue(/aria-label=|<title[ >]/.test(assets[id]),'SVG sans description : '+id);}
  else if(r.kind==='image'){issue(typeof r.alt==='string'&&r.alt.length>0,'Image sans description : '+id);const mime={'png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp'}[path.split('.').pop()];issue(!!mime,'Image non supportée '+id);assets[id]=`<figure class="example"><img style="max-width:100%;height:auto" alt="${String(r.alt||'').replace(/[&<>"']/g,c=>'&#'+c.charCodeAt(0)+';')}" src="data:${mime};base64,${readFileSync(path).toString('base64')}"></figure>`;}
  else errors.push('Type de ressource inconnu : '+id);
 if(r.sourceRefs)for(const ref of r.sourceRefs){issue(documents.has(ref.documentId)&&!!(ref.pages||ref.section),'Source visuelle invalide : '+id);}
 if(r.origin==='teacher-original')issue(Array.isArray(r.sourceRefs)&&r.sourceRefs.length>0,'Source originale absente : '+id);
 if(assets[id]&&(r.caption||r.observe||r.takeaway||r.sourceRefs||r.zoomable)){
 const original=assets[id],source=(r.sourceRefs||[]).map(ref=>[documents.get(ref.documentId)?.title,ref.pages?'p. '+ref.pages:ref.section].filter(Boolean).join(' — ')).join('; ');
 assets[id]=`<section class="learning-visual">${r.caption?`<h3>${esc(r.caption)}</h3>`:''}${original}${r.observe?`<p><b>Observe :</b> ${esc(r.observe)}</p>`:''}${r.takeaway?`<p><b>À retenir :</b> ${esc(r.takeaway)}</p>`:''}${source?`<p class="small">Source : ${esc(source)}</p>`:''}${r.zoomable?`<details class="visual-zoom"><summary>Agrandir l’image</summary><div class="visual-scroll" tabindex="0" role="region" aria-label="Image agrandie">${original}</div></details>`:''}</section>`;
 }

 }
 const refs=(list,label)=>{issue(Array.isArray(list)&&list.length>0,'Source absente : '+label);for(const r of list||[]){issue(documents.has(r.documentId),'Document inconnu : '+label);issue(!!(r.pages||r.section),'Page/section absente : '+label);}};
 const linked=(ids,m,label)=>{issue(Array.isArray(ids),label+' : liste absente');for(const id of ids||[])issue(m.has(id),label+' : lien inconnu '+id);};
 const resource=(id,label,required=false)=>{if(required||id)issue(!!resources[id],'Ressource absente : '+label+' '+id);};
 for(const l of lessons.values()){refs(l.sourceRefs,l.id);issue(!!config.themes?.[l.theme],'Thème inconnu '+l.id);for(const k of ['core','example','title'])issue(typeof l[k]==='string'&&l[k].length>0,'Leçon incomplète '+l.id+' '+k);for(const k of ['core','example','overview','takeaway','more'])if(l[k])safeMarkup(l[k],l.id);for(const p of l.parts||[]){safeMarkup(p.body,l.id);resource(p.resourceId,l.id);}if(!l.afterCoreResource&&!l.afterExampleResource&&!(l.parts||[]).some(p=>p.resourceId)&&!l.activityId)warnings.push('Illustration pédagogique à examiner : '+l.id);resource(l.afterCoreResource,l.id);resource(l.afterExampleResource,l.id);if(l.activityId)issue(activities.has(l.activityId),'Activité absente '+l.id);}
 const checkQ=(q,owner)=>{issue(lessons.has(q.lessonId),'Leçon inconnue '+owner);refs(q.sourceRefs,owner);issue(!!config.themes?.[q.t],'Thème inconnu '+owner);issue(typeof q.q==='string'&&typeof q.writtenPrompt==='string'&&q.q&&q.writtenPrompt,'Énoncé absent '+owner);issue(Array.isArray(q.o)&&q.o.length>=2&&new Set(q.o).size===q.o.length,'Choix invalides '+owner);issue(Number.isInteger(q.a)&&q.a>=0&&q.a<q.o?.length,'Bonne réponse invalide '+owner);issue(Array.isArray(q.accepted)&&q.accepted.length>0,'Réponses écrites absentes '+owner);issue(!!q.e&&!!q.hint&&!!q.tutorial,'Correction/indice/tutoriel absent '+owner);issue(['aliases','unordered-terms','formula','matching'].includes(q.grading?.type),'Correcteur inconnu '+owner);if(q.grading?.type==='unordered-terms')issue(Array.isArray(q.grading.groups)&&q.grading.groups.length>0,'Groupes de correction absents '+owner);if(q.responseType==='development')issue(Array.isArray(q.rubric)&&q.rubric.length>0&&q.rubric.every(r=>typeof r==='string'&&r.length>0),'Grille de développement absente '+owner);if(q.responseType==='number')issue(q.grading?.numeric===true&&Number.isFinite(q.numericAnswer?.value)&&Array.isArray(q.numericAnswer?.units),'Réponse numérique invalide '+owner);if(q.type==='multi-select'){const opts=q.multiSelect?.options||[],good=q.multiSelect?.correctIds||[];issue(opts.length>=2&&new Set(opts.map(o=>o.id)).size===opts.length&&opts.every(o=>idOK(o.id)&&typeof o.label==='string'),'Cases invalides '+owner);issue(good.length>0&&good.length<opts.length&&new Set(good).size===good.length&&good.every(id=>opts.some(o=>o.id===id)),'Bonnes cases invalides '+owner);}if(q.type==='matching'){issue(q.grading?.type==='matching'&&Array.isArray(q.matching?.items)&&Array.isArray(q.matching?.terms),'Associations invalides '+owner);const terms=new Set((q.matching?.terms||[]).map(t=>t.id));for(const item of q.matching?.items||[])issue(terms.has(item.answerId)&&q.grading.pairs?.[item.id]===item.answerId,'Association sans bonne réponse '+owner);}
resource(q.feedbackResource,owner,true);resource(q.promptResource,owner,q.requiresVisual===true);if(q.requiresVisual===true)issue(['observe','locate','recall'].includes(q.visualTask),'Usage du visuel absent : '+owner);if(!q.promptResource&&/sur la carte|selon le graphique|observe.{0,20}(image|carte|schéma)|ci-dessous/i.test(q.q+' '+q.writtenPrompt))warnings.push('Énoncé possiblement dépendant d’un visuel absent : '+owner);linked(q.objectiveIds||[],objectives,owner);linked(q.inventoryIds||[],inventory,owner);};
 for(const q of questions.values()){checkQ(q,q.id);const vars=data.variants?.[q.id]||[];const seen=new Set();for(const v of vars){issue(v.id===q.id&&idOK(v.variantId)&&v.variantId!=='base'&&!seen.has(v.variantId),'Variante invalide '+q.id);seen.add(v.variantId);issue(Number.isInteger(v.level)&&v.level>=1&&v.level<=config.variantPolicy?.maxLevel,'Degré invalide '+q.id);checkQ(v,q.id+'/'+v.variantId);}}
 for(const id of Object.keys(data.variants||{}))issue(questions.has(id),'Variantes sans question '+id);
 const coverage={objectives:[],inventory:[],unresolved:[],missingLessons:[],missingQuestions:[]};
 for(const o of objectives.values()){refs(o.sourceRefs,o.id);linked(o.lessonIds,lessons,o.id);linked(o.questionIds,questions,o.id);const taught=o.lessonIds.length>0,assessed=o.questionIds.length>0;coverage.objectives.push({id:o.id,title:o.title,taught,assessed});issue(taught&&assessed,'Objectif non couvert '+o.id);for(const id of o.questionIds)issue(questions.get(id)?.objectiveIds.includes(o.id),'Lien objectif/question non réciproque '+o.id);}
 for(const item of inventory.values()){refs(item.sourceRefs,item.id);linked(item.lessonIds,lessons,item.id);linked(item.questionIds,questions,item.id);const row={id:item.id,title:item.title,kind:item.kind,taught:item.lessonIds.length>0,assessed:item.questionIds.length>0,status:item.status,note:item.note};coverage.inventory.push(row);if(item.status!=='reviewed')coverage.unresolved.push(row);if(!row.taught)coverage.missingLessons.push(row);if(!row.assessed)coverage.missingQuestions.push(row);}
 for(const a of activities.values()){issue(a.type==='gallery','Type d’activité inconnu '+a.id);const items=map(a.items,'Option activité');issue(items.size>0&&items.has(a.defaultItemId),'Option initiale absente '+a.id);for(const i of items.values())resource(i.resourceId,a.id,true);}
 linked(config.finalQuestionIds,questions,'Quiz final');issue(new Set(config.finalQuestionIds).size===config.finalQuestionIds.length,'Questions finales dupliquées');for(const o of objectives.values())issue(o.questionIds.some(id=>config.finalQuestionIds.includes(id)),'Objectif absent du quiz final '+o.id);
 for(const qid of config.finalQuestionIds)issue(questions.get(qid)?.objectiveIds.length>0,'Question finale sans objectif '+qid);
 if(config.quizPaths){issue(!!config.quizPaths[config.defaultQuizPath],'Parcours par défaut inconnu');for(const [id,path] of Object.entries(config.quizPaths)){issue(typeof path.label==='string'&&Array.isArray(path.entries)&&path.entries.length>0,'Parcours invalide '+id);issue(new Set((path.entries||[]).map(e=>e.slotId)).size===path.entries?.length,'Emplacements du parcours dupliqués '+id);for(const entry of path.entries||[]){issue(idOK(entry.slotId),'Emplacement du parcours invalide '+id);const q=questions.get(entry.questionId);issue(!!q&&q.objectiveIds.includes(entry.objectiveId),'Lien requis du parcours invalide '+id);issue(Number.isInteger(entry.level)&&entry.level>=1&&entry.level<=config.variantPolicy.maxLevel,'Degré du parcours invalide '+id);if(entry.variantId)issue(entry.variantId==='base'||(data.variants?.[entry.questionId]||[]).some(v=>v.variantId===entry.variantId),'Variante du parcours inconnue '+id);}for(const o of objectives.values())issue(path.entries?.some(e=>e.objectiveId===o.id),'Requis absent du parcours '+id+'/'+o.id);}}
 if(config.reviewQuestionIds){linked(config.reviewQuestionIds,questions,'Parcours complet');issue(new Set(config.reviewQuestionIds).size===config.reviewQuestionIds.length,'Doublon parcours complet');issue(Number.isInteger(config.reviewBatchSize)&&config.reviewBatchSize>0,'Taille de série invalide');for(const q of questions.values())issue(config.reviewQuestionIds.includes(q.id),'Question exclue du parcours complet '+q.id);}
 const p=config.variantPolicy;issue(['fixed','preserve-existing'].includes(p?.mode),'Politique de variantes invalide');for(const key of ['maxLevel','successes','distinctVariants','fallbackFailures'])issue(Number.isInteger(p?.[key])&&p[key]>0,'Politique invalide '+key);
 if(coverage.unresolved.length)warnings.push(coverage.unresolved.length+' éléments sources restent à confirmer.');if(coverage.missingQuestions.length)warnings.push(coverage.missingQuestions.length+' éléments inventoriés sans question dédiée.');
 coverage.summary={objectives:objectives.size,coveredObjectives:coverage.objectives.filter(r=>r.taught&&r.assessed).length,inventory:inventory.size,taught:coverage.inventory.filter(r=>r.taught).length,assessed:coverage.inventory.filter(r=>r.assessed).length,unresolved:coverage.unresolved.length,complete:coverage.inventory.every(r=>r.taught&&r.assessed&&r.status==='reviewed')};
 return {errors,warnings,coverage,assets};
}
